CREATE TABLE dbo.Batch
(
	BatchId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	DepartmentId UNIQUEIDENTIFIER NOT NULL,
	RegulationId UNIQUEIDENTIFIER NOT NULL,
	BatchName NVARCHAR(255) NOT NULL,
	BatchCode NVARCHAR(50) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL

	CONSTRAINT FK_Batch_Department FOREIGN KEY (DepartmentId) REFERENCES dbo.Department(DepartmentId) ON DELETE CASCADE,

	CONSTRAINT FK_Batch_Regulation FOREIGN KEY (RegulationId) REFERENCES dbo.Regulation(RegulationId) ON DELETE CASCADE
);