CREATE TABLE Course
(
	CourseId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Courses PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	CourseName NVARCHAR(100) NOT NULL UNIQUE,
	CourseCode NVARCHAR(20) NOT NULL UNIQUE,
	CourseDescription NVARCHAR(255) NULL,
	CourseYear INT NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL
);

