CREATE TABLE dbo.Department
(
	DepartmentId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Departments PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	ProgramId UNIQUEIDENTIFIER NOT NULL,
	DepartmentName NVARCHAR(100) NOT NULL UNIQUE,
	DepartmentCode NVARCHAR(20) NOT NULL UNIQUE,
	[Description] NVARCHAR(255) NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL

	CONSTRAINT FK_Department_Program FOREIGN KEY (ProgramId) REFERENCES dbo.Program(ProgramId) ON DELETE CASCADE
);