-- DEGREE (Program) table definition for College Management System

CREATE TABLE dbo.Program
(
	ProgramId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	--CourseId UNIQUEIDENTIFIER NOT NULL,
	ProgramName NVARCHAR(255) NOT NULL,
	ProgramCode NVARCHAR(50) NOT NULL,
	ProgramDescription NVARCHAR(MAX) NULL,
	ProgramDuration INT NOT NULL,
	SemesterCount INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL

	--CONSTRAINT FK_Program_Courses FOREIGN KEY (CourseId) REFERENCES dbo.Courses(CourseId) ON DELETE CASCADE
);

ALTER TABLE Program DROP CONSTRAINT FK_Program_Courses, COLUMN CourseId;

EXEC sp_help 'Program'; 



