CREATE TABLE dbo.Roles
(
	RoleId          UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Roles PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	RoleName        NVARCHAR(50)  NOT NULL UNIQUE,
	[Description]   NVARCHAR(255) NULL,
	IsActive        BIT NOT NULL DEFAULT 1,
	CreatedAt       DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy       UNIQUEIDENTIFIER NULL,
	UpdatedAt       DATETIME2 NULL,
	UpdatedBy       UNIQUEIDENTIFIER NULL
);