CREATE TABLE dbo.Semester
(
	SemesterId UNIQUEIDENTIFIER CONSTRAINT PK_Semester PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	SemesterName NVARCHAR(255) NOT NULL,
	SemesterCode NVARCHAR(50) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL
);