CREATE TABLE dbo.Staff
(
	StaffId UNIQUEIDENTIFIER CONSTRAINT PK_Staff PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	StaffCode NVARCHAR(50) NOT NULL UNIQUE,
	UserId UNIQUEIDENTIFIER NOT NULL,
	DepartmentId UNIQUEIDENTIFIER NULL,
	DesignationId UNIQUEIDENTIFIER NOT NULL,
	JoiningDate DATE NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,

	CONSTRAINT FK_Staff_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId),
	CONSTRAINT FK_Staff_Department FOREIGN KEY (DepartmentId) REFERENCES dbo.Department(DepartmentId),
	CONSTRAINT FK_Staff_Designation FOREIGN KEY (DesignationId) REFERENCES dbo.Designation(DesingationId)
);