CREATE TABLE dbo.Student
(
	StudentId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Student PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	EnrollNo INT NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Phone NVARCHAR(20) NULL,
	DateOfBirth DATE NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,


	DepartmentId UNIQUEIDENTIFIER NOT NULL,
	BatchId UNIQUEIDENTIFIER NOT NULL,
	SemesterId UNIQUEIDENTIFIER NOT NULL,


	CONSTRAINT FK_Student_Department FOREIGN KEY (DepartmentId) REFERENCES dbo.Department(DepartmentId) ON DELETE CASCADE,
	CONSTRAINT FK_Student_Batch FOREIGN KEY (BatchId) REFERENCES dbo.Batch(BatchId) ON DELETE NO ACTION,
	CONSTRAINT FK_Student_Semester FOREIGN KEY (SemesterId) REFERENCES dbo.Semester(SemesterId) ON DELETE CASCADE

);