CREATE TABLE dbo.Subject
(
	SubjectId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Subject PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	SubjectName NVARCHAR(255) NOT NULL,
	SubjectCode NVARCHAR(50) NOT NULL,
	SubjectDescription NVARCHAR(MAX) NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME2 NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL
);