CREATE TABLE dbo.User_Role_XRef
(
	UserRoleId      UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_UserRole_XRef PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	UserId          UNIQUEIDENTIFIER NOT NULL,
	RoleId          UNIQUEIDENTIFIER NOT NULL,
	IsActive        BIT NOT NULL DEFAULT 1,
	AssignedAt      DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	AssignedBy      UNIQUEIDENTIFIER NULL,

	--PRIMARY KEY (UserId, RoleId),
	FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId) ON DELETE CASCADE,
	FOREIGN KEY (RoleId) REFERENCES dbo.Roles(RoleId) ON DELETE CASCADE
)